### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [digikar99/dense-arrays#1]
Building with SBCL 2.3.1.122-1455d60f6 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 399b9e84c5a5a4c153bccfd479ee1bfa28e1c902

*dense-arrays-plus-lite* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001728003}>: Component "extensible-compound-types-interfaces" not found, required by #<SYSTEM "trivial-coerce">

```

*dense-arrays-plus* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001728003}>: Component "extensible-compound-types-interfaces" not found, required by #<SYSTEM "trivial-coerce">

```

[Full log here](http://report.quicklisp.org/2023-03-22/failure-report/dense-arrays.html)

**Comment by digikar99** [comment]
[8f0f92b4684592f9478ab60796ce4ce18c44a0c9](https://github.com/digikar99/extensible-compound-types/commit/8f0f92b4684592f9478ab60796ce4ce18c44a0c9) should fix the issue; please confirm.

**Comment by digikar99** [comment]
I'm closing this since another build attempt is being made.
